const slugsdata = [
  "andhra-pradesh",
  "arunachal-pradesh",
  "assam",
  "bihar",
  "chhattisgarh",
  "goa",
  "gujarat",
  "haryana",
  "himachal-pradesh",
  "jharkhand",
  "karnataka",
  "kerala",
  "madhya-pradesh",
  "maharashtra",
  "manipur",
  "meghalaya",
  "mizoram",
  "nagaland",
  "odisha",
  "punjab",
  "rajasthan",
  "sikkim",
  "tamil-nadu",
  "telangana",
  "tripura",
  "uttar-pradesh",
  "uttarakhand",
  "west-bengal",
  "andaman-and-nicobar-islands",
  "chandigarh",
  "dadra-and-nagar-haveli-and-daman-and-diu",
  "delhi",
  "jammu-and-kashmir",
  "ladakh",
  "lakshadweep",
  "puducherry",
  "northeast-states",
  "winter-trips",
  "summer-trips",
  "autumn-trips",
  "monsoon-trips",
  "digital-detox",
  "exploration",
  "peace-and-calm",
  "for-adventure",
  "curiosity",
];

const StateList = {
  "Andhra Pradesh": "",
  "Arunachal Pradesh": "",
  "Assam": "",
  "Bihar": "",
  "Chhattisgarh": "",
  "Goa": "",
  "Gujarat": "",
  "Haryana": "",
  "Himachal Pradesh": "Snow treks, cozy villages, mountain escapes.",
  "Jharkhand": "",
  "Karnataka": "",
  "Kerala": "Backwaters, ayurveda retreats, eco-travel.",
  "Madhya Pradesh": "Wildlife safaris, heritage cities, tribal culture.",
  "Maharashtra": "",
  "Manipur": "",
  "Meghalaya": "",
  "Mizoram": "",
  "Nagaland": "",
  "Odisha": "",
  "Punjab": "",
  "Rajasthan": "Desert adventures, royal palaces, heritage walks.",
  "Sikkim": "",
  "Tamil Nadu": "",
  "Telangana": "",
  "Tripura": "",
  "Uttar Pradesh": "Spiritual journeys in Varanasi, Mathura, Ayodhya.",
  "Uttarakhand": "Himalayan treks, Char Dham yatra, forest retreats.",
  "West Bengal": "",
  // Union Territories
  "Andaman and Nicobar Islands": "",
  "Chandigarh": "",
  "Dadra and Nagar Haveli and Daman and Diu": "",
  "Delhi": "",
  "Jammu and Kashmir": "",
  "Ladakh": "",
  "Lakshadweep": "",
  "Puducherry": "",
  // Custom grouping
  "Northeast States": "Ziro, Majuli, Shillong & hidden cultural gems."
};

export default StateList
export {slugsdata}